VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Report_LR0052_M00"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
'****************************  strat or program ********************************
'==============================================================================*
'
'        SYSTEM_NAME     : 未収管理システム
'        SUB_SYSTEM_NAME :
'
'        PROGRAM_NAME    :
'        PROGRAM_ID      :
'        PROGRAM_KBN     : REPORT
'
'        CREATE          : 2001/08/09
'        CERATER         : N.MIURA
'
'        UPDATE          :
'        UPDATER         :
'                        :
'
'==============================================================================*
Option Compare Database
Option Explicit
'****************************  ended or program ********************************


